### ISSUE TITLE
Setup Metabase

### ISSUE THREAD

**Issue by princiya** [zalando/ost#113]
## Setup Metabase

Setup metabase with proper instructions and documentation.

### Tasks

- [x] Install and run Metabase
- [x] Connect Metabase to Roadbloak
- [x] Write setup instructions [Mac] https://metabase.com/start/mac.html
- [x] ~~Check Postgres integration~~ #118 

### Expected delivery

Metabase is up and running and is able to visualise monitoring data from Roadblock.
