### ISSUE TITLE
PostgreSQL for Roadblock

### ISSUE THREAD

**Issue by princiya** [zalando/ost#118]
## PostgreSQL for Roadblock

The current implementation for Roadblock uses SQLite. This issue is to try Roadblock on PostgreSQL, and integrate with Metabase

### Tasks

- [ ] Connect Roadblock to PostgreSQL database
- [ ] Connect Metabase to this PostgreSQL database
- [ ] Run Metabase and PostgreSQL on Docker

### Expected delivery

PostgreSQL support for Roadblock
