### ISSUE TITLE
Get employee data on joining and leaving dates

### ISSUE THREAD

**Issue by perploug** [zalando/ost#130]
## Task Headline

We need to know who is a external contributor and who is a member of the zalando organisation, so we can track how many community members are converted to zalando organisation members. 

Based on our Github data - we cannot currently say precisely if a contribution was made by a employee of zalando, a external contributor, or a former employee. 

We must compare our internal SAP data with github data to get a better view of who worked at zalando at what to time, to know for sure. 

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [x] Find the department responsible for this data
- [ ] Get the data
- [ ] Combine with our current source of Github data
- [ ] Build Metabase question

### Expected delivery

What is the concrete outcome of this work: 

A metabase question which gives us a number on how many community members have been converted to organisation members within a given timeframe

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [ ] People analytics?

## How do we measure the task was completed
How do we measure impact 

  1. Metabase dashboard

**Comment by perploug** [comment]
This is likely a long running task - so starting to as around today to track down who could have this data.

**Comment by perploug** [comment]
Blocked as I truly know nothing about how to configure Ztokens for access to the people api.
