### ISSUE TITLE
Open source principles page

### ISSUE THREAD

**Issue by perploug** [zalando/ost#180]
## Get the principles page under Zalando ownership

The open source guild links to a principals page, which haven't been updated for ages:
https://zalando-open-source-principles.readthedocs.io/en/latest/

The source of this page is on a former employees github page:
https://github.com/elezar/open-source-principles

While the principals is fine on their own, the document should be updated to reflect where we are now and become part of the SSOT (single source of truth) 

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [ ] Figure out if we can take ownership of the readthedocs page
- [ ] Review the content
- [ ] Discuss the principals with the guild - do they still apply? 
- [ ] Figure out where this should be stored going forward

### Expected delivery

What is the concrete outcome of this work: principals page on opensource.zalando or on the guild page - or the removal of the principals page - depending on discussions

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [ ] OS Guild

**Comment by perploug** [comment]
Look at how we could migrate these principles to either the frontpage of opensource.zalando.com or to a subpage (not under /docs)
