### ISSUE TITLE
Define incubator graduation guidelines

### ISSUE THREAD

**Issue by perploug** [zalando/ost#73]
## Description

Publish what defines a good open source project and what the process for a project is to graduate
from the incubator.

- what rules needs to be followed
- what is best practices
- what a the key quality indicators we look for
- how long does a project have to reach these goals
- what happens if goals are not met

### Tasks
This is the concreate tasks to complete before the task is marked as done

- [x] Write down rules for incubator projects
- [x] Indicators for quality projects on the incubator
- [ ] Timeframe for graduation
- [ ] What happens if a project does not graduate within timeframe

### Expected delivery

Graduation guidelines for the review group published on the ost website
